quarkus:
  mailer:
    from: test@test.org
    host: localhost
    port: 3025
    ssl: false
    username: test
    password: test
    mock: false
  datasource:
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://localhost:3306/portal?ServerTimezone=UTC
      enable-metrics: true
    username: portal
    password: portal4Dev
    health:
      enabled: true
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
    sql-load-scripts: no-file
  liquibase:
    migrate-at-start: true

# Configure the SmallRye Kafka connector
mp:
  messaging:
    incoming:
      email-in:
        connector: smallrye-kafka
        bootstrap:
          servers: localhost:9092
        topic: email
        value:
          serializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
        failure-strategy: dead-letter-queue