quarkus:
  datasource:
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://localhost:3306/portal?ServerTimezone=UTC
      enable-metrics: true
    username: portal
    password: portal4Dev
    health:
      enabled: true
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
    sql-load-scripts: no-file

# Configure the SmallRye Kafka connector
mp:
  messaging:
    outgoing:
      command-out:
        connector: smallrye-kafka
        bootstrap:
          servers: localhost:9092
        topic: command
        value:
          serializer: io.vertx.kafka.client.serialization.JsonObjectSerializer