quarkus:
  datasource:
    db-kind: mysql
    jdbc:
      url: jdbc:mysql://localhost:3306/portal?ServerTimezone=UTC
      enable-metrics: true
    username: portal
    password: portal4Dev
    health:
      enabled: true
  hibernate-orm:
    database:
      generation: none
    log:
      sql: true
    sql-load-scripts: no-file
  quartz:
    clustered: true
    store-type: jdbc-cmt
    plugins:
      jobHistory:
        class: org.quartz.plugins.history.LoggingJobHistoryPlugin
        properties:
          jobSuccessMessage: "Job [{1}.{0}] execution complete and reports: {8}"
  liquibase:
    migrate-at-start: true
  log:
    console:
      json: false
      format: '%d{YYYY-MM-dd HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n'

# Configure the SmallRye Kafka connector
mp:
  messaging:
    outgoing:
      sync-out:
        connector: smallrye-kafka
        bootstrap:
          servers: localhost:9092
        topic: sync
        value:
          serializer: org.apache.kafka.common.serialization.StringSerializer